on:
  pull_request:
    types: [opened, synchronize]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '12'
      - name: ESLint
        uses: betrybe/eslint-linter-action@v2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  evaluator_job:
    name: Evaluator Job
    runs-on: ubuntu-18.04
    needs: [eslint]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 'password'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Evaluator Step
        uses: betrybe/jest-evaluator-action@v5
        id: evaluator
        with:
          repository-test-name: 'betrybe/sd-0x-mysql-all-for-one-tests'
          repository-test-branch: 'Improvement/general'
        env:
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: 'password'
          HOSTNAME: 'mysql'

      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v2
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: staging
          pr-number: ${{ github.event.number }}
